spring.application.name=login-auth-api

server.port=3333

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

api.infra.sec.token.algorithm.secret=CHANGE-ME-TO-A-SECURE-RANDOM-STRING


